// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Photo struct {
	ID        uuid.UUID          `json:"id"`
	Bucket    string             `json:"bucket"`
	AssetID   string             `json:"asset_id"`
	Width     int32              `json:"width"`
	Height    int32              `json:"height"`
	Size      int32              `json:"size"`
	OwnerID   *uuid.UUID         `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int32              `json:"version"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}
